[package]
authors = ["voidpumpkin <32368314+voidpumpkin@users.noreply.github.com>"]
edition = "2021"
name = "structural-convert"
description = "Derive conversion traits when items are structurally similar"
version = "0.1.0"
license = "MIT"
license-file = "LICENSE"
repository = "https://github.com/voidpumpkin/structural-convert/"
readme = "README.md"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
rustc-workspace-hack = "1.0.0"
syn = { version = "1", features = ["extra-traits"] }
darling = "0.14.4"
